const TOPICS=[...new Set(ALL_Q.map(q=>q.cat))].sort((a,b)=>a.localeCompare(b,'es'));
const STORAGE_KEY='prepseguro_utah_progress_v2';
let mode='practice',qOrder=[],current=0,answers={},optOrder={},examSilent=false;
let profile=loadProfile();
let lastFocusedQi=null;
function loadProfile(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');return saved&&typeof saved==='object'?saved:{}}catch(e){return {}}}
function saveProfile(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(profile))}catch(e){}}
function topicStats(cat){const r=profile[cat]||{a:0,c:0};return {a:Number(r.a)||0,c:Number(r.c)||0,p:(Number(r.a)||0)?Math.round((Number(r.c)||0)/(Number(r.a)||0)*100):null}}
function weakTopics(){return TOPICS.filter(cat=>{const s=topicStats(cat);return s.a>=2&&s.p<70})}
function escapeHtml(v){return String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function shuffle(a){const c=[...a]; for(let i=c.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[c[i],c[j]]=[c[j],c[i]]} return c}
function pctColor(p){return p<50?'#dc2626':p<60?'#f59e0b':p<75?'#84cc16':'#16a34a'}
function statusTag(cat){const s=topicStats(cat);if(!s.a)return '<span class="tag">Sin datos</span>';return s.p<50?'<span class="tag weak">Refuerzo prioritario</span>':s.p<70?'<span class="tag mid">Seguir practicando</span>':'<span class="tag ok">Buen dominio</span>'}
function init(){renderDiag();renderTopicChecks();updateStats();}
function setMenu(id){document.querySelectorAll('.menu button').forEach(b=>b.classList.remove('active')); const el=document.getElementById('m-'+id); if(el) el.classList.add('active');}
function showSection(s){document.getElementById('home').classList.add('hidden');document.getElementById('practice').classList.add('hidden');document.getElementById('quiz').classList.add('hidden');document.getElementById(s).classList.remove('hidden');setMenu(s==='home'?'home':'practice');}
function renderDiag(){const counts={};ALL_Q.forEach(q=>counts[q.cat]=(counts[q.cat]||0)+1);document.getElementById('diag').innerHTML='<div class="topic-grid">'+TOPICS.map(cat=>{const s=topicStats(cat),shown=s.p===null?'—':s.p+'%',width=s.p===null?0:s.p,color=s.p===null?'#cbd5e1':pctColor(s.p);return `<div class="topic"><div class="topic-row"><h4>${escapeHtml(cat)}</h4><b style="color:${color}">${shown}</b></div><div class="topic-row"><span>${counts[cat]||0} disponibles · ${s.a} respondidas</span>${statusTag(cat)}</div><div class="bar"><div class="fill" style="width:${width}%;background:${color}"></div></div></div>`}).join('')+'</div>';}
function renderTopicChecks(){const counts={};ALL_Q.forEach(q=>counts[q.cat]=(counts[q.cat]||0)+1);const weak=weakTopics();document.getElementById('topicChecks').innerHTML=TOPICS.map(cat=>`<label class="btn" style="cursor:pointer"><input type="checkbox" class="topicBox" value="${escapeHtml(cat)}" ${weak.includes(cat)?'checked':''}> ${escapeHtml(cat)} (${counts[cat]||0})</label>`).join('');}
function selectWeak(){const weak=weakTopics();document.querySelectorAll('.topicBox').forEach(b=>b.checked=weak.includes(b.value));if(!weak.length)alert('Aún no hay suficientes respuestas para detectar áreas débiles. Haz primero una práctica o un simulacro.');}
function selectAllTopics(){document.querySelectorAll('.topicBox').forEach(b=>b.checked=true);}
function weightedWeakOrder(){const weak=weakTopics();if(!weak.length)return shuffle(ALL_Q.map((_,i)=>i)).slice(0,25);return shuffle(ALL_Q.map((q,i)=>weak.includes(q.cat)?i:null).filter(i=>i!==null)).slice(0,40)}
function startMode(m){mode=m;answers={};optOrder={};current=0;if(m==='exam'){const size=Math.min(Number(document.getElementById('examSize')?.value)||50,ALL_Q.length);qOrder=shuffle(ALL_Q.map((_,i)=>i)).slice(0,size);examSilent=true;document.getElementById('modeLabel').textContent=`Simulacro de ${size} preguntas: las respuestas se mostrarán al terminar.`;setMenu('exam')}else if(m==='weak'){const weak=weakTopics();qOrder=weightedWeakOrder();examSilent=false;document.getElementById('modeLabel').textContent=weak.length?'Refuerzo personalizado: '+weak.join(', ')+'.':'Sesión diagnóstica: responde estas preguntas para detectar tus áreas de refuerzo.';setMenu('weak')}document.getElementById('home').classList.add('hidden');document.getElementById('practice').classList.add('hidden');document.getElementById('quiz').classList.remove('hidden');renderQ();window.scrollTo({top:0,behavior:'smooth'})}
function startCustom(){const selected=[...document.querySelectorAll('.topicBox')].filter(b=>b.checked).map(b=>b.value);if(!selected.length){alert('Selecciona al menos un tema.');return}mode='custom';answers={};optOrder={};current=0;examSilent=false;qOrder=shuffle(ALL_Q.map((q,i)=>selected.includes(q.cat)?i:null).filter(x=>x!==null));document.getElementById('modeLabel').textContent='Práctica por tema: '+selected.length+' tema(s).';document.getElementById('practice').classList.add('hidden');document.getElementById('quiz').classList.remove('hidden');setMenu('practice');renderQ();window.scrollTo({top:0,behavior:'smooth'})}
function startWrong(){const wrong=Object.keys(answers).filter(k=>!k.includes('_')&&answers[k]===false).map(Number);if(!wrong.length){alert('Todavía no tienes preguntas falladas.');return;}qOrder=shuffle(wrong);current=0;examSilent=false;document.getElementById('modeLabel').textContent='Repaso de incorrectas.';renderQ();}
function resetSession(){if(confirm('¿Reiniciar esta sesión? Tu progreso histórico se conservará.')){answers={};optOrder={};current=0;renderQ()}}
function clearProgress(){if(confirm('¿Borrar todo el progreso guardado en este dispositivo?')){profile={};saveProfile();renderDiag();renderTopicChecks();updateStats()}}
function shuffleCurrent(){qOrder=shuffle(qOrder);current=0;renderQ();}
function getOptions(i){if(!optOrder[i])optOrder[i]=shuffle(ALL_Q[i].opts);return optOrder[i];}
function updateStats(){let total=0,correct=0;Object.values(profile).forEach(r=>{total+=Number(r.a)||0;correct+=Number(r.c)||0});const wrong=total-correct;document.getElementById('s-total').textContent=total;document.getElementById('s-correct').textContent=correct;document.getElementById('s-wrong').textContent=wrong;document.getElementById('s-pct').textContent=total?Math.round(correct/total*100)+'%':'—';if(qOrder.length){const p=Math.round((current+1)/qOrder.length*100);document.getElementById('prog').style.width=p+'%';document.getElementById('progLabel').textContent='Pregunta '+(current+1)+' de '+qOrder.length+' · '+p+'%'}}
function renderQ(){updateStats();if(!qOrder.length){document.getElementById('questionArea').innerHTML='<div class="panel notice">No hay preguntas en esta selección.</div>';return}const qi=qOrder[current],q=ALL_Q[qi],opts=getOptions(qi),answered=answers[qi]!==undefined,selected=answers[qi+'_sel'];let optsHtml=opts.map((opt,idx)=>{let cls='opt';if(answered&&!examSilent){if(opt===q.ans)cls+=' correct';if(opt===selected&&opt!==q.ans)cls+=' wrong'}return `<button type="button" class="${cls}" ${answered?'disabled':''} onclick="choose(${qi}, ${idx})">${String.fromCharCode(65+idx)}. ${escapeHtml(opt)}</button>`}).join('');let fb='';if(answered&&!examSilent){const ok=answers[qi]===true,s=topicStats(q.cat);fb=`<div class="feedback"><div class="fb-header ${ok?'correct':'wrong'}">${ok?'✓ Correcto':'✗ Incorrecto — Respuesta correcta: '+escapeHtml(q.ans)}</div><div class="fb-body"><b>Tema:</b> ${escapeHtml(q.cat)}<br><b>Tu progreso en este tema:</b> ${s.p===null?'Sin datos':s.p+'%'} (${s.c}/${s.a}).<br><br><div class="fb-why"><b>📖 ¿Por qué esta respuesta?</b><br>${escapeHtml(q.why||'')}</div></div></div>`}document.getElementById('questionArea').innerHTML=`<div class="q-card"><div class="q-meta"><span class="tag">#${q.id}</span><span>${escapeHtml(q.cat)}</span>${statusTag(q.cat)}</div><div class="q-text" id="q-heading" tabindex="-1">${escapeHtml(q.q)}</div><div class="options">${optsHtml}</div>${fb}</div>`;if(qi!==lastFocusedQi){lastFocusedQi=qi;var _qh=document.getElementById("q-heading");if(_qh){try{_qh.focus({preventScroll:true})}catch(e){_qh.focus()}}}}
function choose(qi,optIndex){const opts=getOptions(qi),sel=opts[optIndex];if(answers[qi]!==undefined)return;const ok=sel===ALL_Q[qi].ans;answers[qi]=ok;answers[qi+'_sel']=sel;const cat=ALL_Q[qi].cat,s=profile[cat]||{a:0,c:0};profile[cat]={a:(Number(s.a)||0)+1,c:(Number(s.c)||0)+(ok?1:0)};saveProfile();renderDiag();if(examSilent){if(current<qOrder.length-1){current++;renderQ()}else finish()}else renderQ()}
function prevQ(){if(current>0){current--;renderQ();}}
function nextQ(){if(current<qOrder.length-1){current++;renderQ();}else finish();}
function finish(){updateStats();renderDiag();renderTopicChecks();const answered=qOrder.filter(i=>answers[i]!==undefined).length,correct=qOrder.filter(i=>answers[i]===true).length,pct=answered?Math.round(correct/answered*100):0;const by={};qOrder.forEach(i=>{const q=ALL_Q[i];if(!by[q.cat])by[q.cat]={a:0,c:0};if(answers[i]!==undefined){by[q.cat].a++;if(answers[i]===true)by[q.cat].c++}});const rows=Object.keys(by).sort((a,b)=>(by[a].c/(by[a].a||1))-(by[b].c/(by[b].a||1))).map(cat=>{const r=by[cat],p=r.a?Math.round(r.c/r.a*100):0,total=topicStats(cat);return `<tr><td>${escapeHtml(cat)}</td><td>${r.c}/${r.a}</td><td><b style="color:${pctColor(p)}">${p}%</b></td><td>${total.p===null?'—':total.p+'%'}</td></tr>`}).join('');const wrongList=qOrder.filter(i=>answers[i]===false).slice(0,20).map(i=>`<li><b>${escapeHtml(ALL_Q[i].cat)}:</b> ${escapeHtml(ALL_Q[i].q)}<br><span class="muted">Correcta: ${escapeHtml(ALL_Q[i].ans)}</span><br><span class="muted">📖 ${escapeHtml(ALL_Q[i].why||'')}</span></li>`).join('');document.getElementById('questionArea').innerHTML=`<div class="panel results"><div class="ring"><b>${pct}%</b><span>${correct}/${answered}</span></div><h2>${pct>=80?'¡Excelente resultado!':pct>=70?'Buen resultado; sigue practicando':'Conviene reforzar antes de presentar'}</h2><p class="muted">Meta recomendada: mantener 80% o más en simulacros y reforzar cualquier tema por debajo de 70%.</p><div class="controls" style="justify-content:center"><button type="button" class="btn orange" onclick="startMode('weak')">Reforzar mis áreas débiles</button><button type="button" class="btn primary" onclick="startMode('exam')">Nuevo simulacro</button><button type="button" class="btn" onclick="startWrong()">Repasar falladas</button><button type="button" class="btn" onclick="showSection('home')">Ver progreso</button></div></div><div class="panel"><h3>Resultado por tema</h3><div class="table-wrap"><table><tr><th>Tema</th><th>Correctas</th><th>Esta sesión</th><th>Histórico</th></tr>${rows}</table></div></div><div class="panel"><h3>Preguntas para repasar</h3><ol style="padding-left:20px;line-height:1.6">${wrongList||'<span class="muted">No registraste preguntas falladas en esta sesión.</span>'}</ol></div>`;window.scrollTo({top:0,behavior:'smooth'})}
init();
